name: Docker Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Read and update version
      id: version
      run: |
        VERSION_FILE="version.txt"
        if [ -f "$VERSION_FILE" ]; then
          VERSION=$(cat $VERSION_FILE)
          IFS='.' read -r -a VERSION_PARTS <<< "$VERSION"
          MAJOR="${VERSION_PARTS[0]}"
          MINOR="${VERSION_PARTS[1]}"
          NEW_MINOR=$((MINOR + 1))
          NEW_VERSION="$MAJOR.$NEW_MINOR"
        else
          NEW_VERSION="1.0"
        fi
        echo "$NEW_VERSION" > $VERSION_FILE
        echo "::set-output name=version::$NEW_VERSION"
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
 
    - name: Build Docker image
      id: docker_build
      run: |
        IMAGE_TAG="1.${{ steps.version.outputs.version }}"
        docker build -t adav07/sample-docker-project:$IMAGE_TAG .
        echo "::set-output name=image_tag::$IMAGE_TAG"
    - name: Push Docker image to Docker Hub
      run: docker push adav07/sample-docker-project:${{ steps.docker_build.outputs.image_tag }}
