name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          adav07/sample-docker-project:latest
          adav07/sample-docker-project:${{ github.sha }}
          adav07/sample-docker-project:${{ env.VERSION }}
      env:
        VERSION: ${{ github.event.release.tag_name }}
